USE [master]
GO

/****** Object:  Database [Final_Eleccion]    Script Date: 3/23/2020 3:49:58 PM ******/
CREATE DATABASE [Final_Eleccion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Final_Eleccion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Final_Eleccion.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Final_Eleccion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Final_Eleccion_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Final_Eleccion] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Final_Eleccion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Final_Eleccion] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Final_Eleccion] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Final_Eleccion] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Final_Eleccion] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Final_Eleccion] SET ARITHABORT OFF 
GO

ALTER DATABASE [Final_Eleccion] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Final_Eleccion] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Final_Eleccion] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Final_Eleccion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Final_Eleccion] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Final_Eleccion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Final_Eleccion] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Final_Eleccion] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Final_Eleccion] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Final_Eleccion] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Final_Eleccion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Final_Eleccion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Final_Eleccion] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Final_Eleccion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Final_Eleccion] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Final_Eleccion] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Final_Eleccion] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Final_Eleccion] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Final_Eleccion] SET  MULTI_USER 
GO

ALTER DATABASE [Final_Eleccion] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Final_Eleccion] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Final_Eleccion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Final_Eleccion] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Final_Eleccion] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Final_Eleccion] SET  READ_WRITE 
GO

